#set directory 
#regression for nuclear diversity in least concern mollusc
pdf("ND_LC_moll.pdf", width=5, height=5)
setwd("~/pre_analysis")
data=read.table("moll_LC.csv", header=T, sep=",")
head(data)
lm.out=lm(range~Observed_Heterozygosity, data=data)
summary(lm.out)
lm.out1=lm(latitude~Observed_Heterozygosity, data=data)
summary(lm.out1)
plot(x=data$range, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out)
plot(x=data$latitude, y=data$Observed_Heterozygosity, xlab="latitude" , ylab="Nuclear diversity")
abline(lm.out1)
dev.off()
sink("ND_LC_moll.txt")
print(summary(lm.out))
print(summary(lm.out1))

#regression for least concern mollusca using mitochodrial diversity 
pdf("MD_LC_moll.pdf", width=5, height=5)
lm.out=lm(range~Nucleotide_diversity, data=data)
summary=lm.out
lm.out=lm(latitude+longitude~Nucleotide_diversity, data=data)
summary(lm.out1)
plot(x=data$range, y=data$Nucleotide_diversity, xlab="range", ylab="Mitochondrial diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Nucleotide_diversity, xlab="latlong", ylab="Mitochondrial diversity")
abline(lm.out1)
dev.off()
sink("MD_LC_moll.txt")
print(summary(lm.out))
print(summary(lm.out1))
sink()

#regression for vulnerable using nuclear diversity in mollusca
pdf("ND_VN_moll.pdf", width=5, height=5)
data=read.table("moll_VN.csv", header=T, sep=",")
lm.out=lm(range~Observed_Heterozygosity, data=data)
summary=lm.out
plot(x=data$range, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out)
lm.out1=lm(latitude+longitude~Observed_Heterozygosity, data=data)
summary(lm.out1)
plot(x=data$latitude+data$longitude, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out1)
dev.off()
sink("ND_VN_moll.txt")
print(summary(lm.out))
print(summary(lm.out1))
#regression for vulnerable mollusc using mitochondrial diversity 
lm.out=lm(range~Nucleotide_diversity, data=data)
summary(lm.out)
lm.out1=lm(latitude+longitude~Nucleotide_diversity, data=data)
summary(lm.out1)
pdf("MD_VN_moll.pdf", width=5, height=5)
plot(x=data$range, y=data$Nucleotide_diversity, xlab="range", ylab="Mitochondrial diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Nucleotide_diversity, xlab="latlong", ylab="Mitochondrial diveristy")
abline(lm.out1)
dev.off()
sink("MD_VN_moll.txt")
print(summary(lm.out))
print(summary(lm.out1)
sink()


#regression for critically endangered species using nuclear diversity
pdf("ND_CE_moll.pdf", width=5, height=5)
data=read.table("moll_CE.csv", header=T, sep=",")
lm.out=lm(range~Observed_Heterozygosity, data=data)
summary=lm.out
lm.out1=lm(latitude+longitude~Observed_Heterozygosity, data=data)
summary(lm.out1)
plot(x=data$range, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out1)
dev.off()
sink("ND_CE_moll.txt")
print(summary(lm.out))
print(summary(lm.out1))

#regression for critically endangered mollusca using nuclear diversity
lm.out=lm(range~Nucleotide_diversity, data=data)
summary=lm.out
lm.out1=lm(latitude+longitude~Nucleotide_diversity, data=data)
summary(lm.out1)
pdf("MD_CE_moll.pdf", width=5, height=5)
plot(x=data$range, y=data$Nucleotide_diversity, xlab="range", ylab="Mitochondrial diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Nucleotide_diversity, xlab="latlong", ylab="Mitochondrial diveristy")
abline(lm.out1)
dev.off()
sink("MD_CE_moll.txt")
print(summary(lm.out))
print(summary(lm.out1))
sink()

#regression in endangered species of mollusc using nuclear diversity 
pdf("ND_EN_moll.pdf", width=5, height=5)
data=read.table("moll_EN.csv", header=T, sep=",")
lm.out=lm(range~Observed_Heterozygosity, data=data)
summary(lm.out)
lm.out1=lm(latitude+longitude~Observed_Heterozygosity, data=data)
summary(lm.out1)
plot(x=data$range, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out1)
dev.off()
sink("ND_EN_moll.txt")
print(summary(lm.out))
print(summary(lm.out1))

#regression for endangered mollusca using mitochondrial diversity
lm.out=lm(range~Nucleotide_diversity, data=data)
summary(lm.out)
lm.out1=lm(latitude+longitude~Nucleotide_diversity, data=data)
summary(lm.out1)
pdf("MD_EN_moll.pdf", width=5, height=5)
plot(x=data$range, y=data$Nucleotide_diversity, xlab="range", ylab="Mitochondrial diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Nucleotide_diversity, xlab="latlong", ylab="Mitochondrial diveristy")
abline(lm.out1)
dev.off()
sink("MD_EN_moll.txt")
print(summary(lm.out))
print(summary(lm.out1))
sink()

#regression for least concern arthropoda using nuclear diveristy 
pdf("ND_LC_arhtro.pdf", width=5, height=5)
data=read.table("arhtro_LC.csv", header=T, sep=",")
lm.out=lm(range~Observed_Heterozygosity, data=data)
summary=lm.out
lm.out1=lm(latitude+longitude~Observed_Heterozygosity, data=data)
summary(lm.out1)
plot(x=data$range, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out1)
dev.off()
sink("ND_LC_arhtro.txt")
print(summary(lm.out))
print(summary(lm.out1))

#regression for least concern arthropoda using mitochondrial diversity
lm.out=lm(range~Nucleotide_diversity, data=data)
summary(lm.out)
lm.out1=lm(latitude+longitude~Nucleotide_diversity, data=data)
summary(lm.out1)
pdf("MD_LC_arhtro.pdf", width=5, height=5)
plot(x=data$range, y=data$Nucleotide_diversity, xlab="range", ylab="Mitochondrial diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Nucleotide_diversity, xlab="latlong", ylab="Mitochondrial diveristy")
abline(lm.out1)
dev.off()
sink("MD_LC_arhtro.txt")
print(summary(lm.out))
print(summary(lm.out1))
sink()

#regression for vulnerable arthropoda using nuclear diveristy
pdf("ND_VN_arthro.pdf", width=5, height=5)
data=read.table("arthro_VN.csv", header=T, sep=",")
lm.out=lm(range~Observed_Heterozygosity, data=data)
summary(lm.out)
lm.out1=lm(latitude+longitude~Observed_Heterozygosity, data=data)
summary(lm.out1)
plot(x=data$range, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out1)
dev.off()
sink("ND_VN_arthro.txt")
print(summary(lm.out))
print(sumamry(lm.out1))

#regression for vulnerbale arthropoda using mitochondrial diveristy 
lm.out=lm(range~Nucleotide_diversity, data=data)
summary(lm.out)
lm.out1=lm(latitude+longitude~Nucleotide_diversity, data=data)
summary(lm.out1)
pdf("MD_VN_arthro.pdf", width=5, height=5)
plot(x=data$range, y=data$Nucleotide_diversity, xlab="range", ylab="Mitochondrial diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Nucleotide_diversity, xlab="latlong", ylab="Mitochondrial diveristy")
abline(lm.out1)
dev.off()
sink("MD_VN_arthro.txt")
print(summary(lm.out))
print(summary(lm.out1))
sink()

#regression for critically endangered arthropoda using nuclear diversity 
pdf("ND_CE_arhtro.pdf", width=5, height=5)
data=read.table("arhtro_CE.csv", header=T, sep=",")
lm.out=lm(range~Observed_Heterozygosity, data=data)
summary(lm.out)
lm.out1=lm(latitude+longitude~Observed_Heterozygosity, data=data)
summary(lm.out1)
plot(x=data$range, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out1)
dev.off()
sink("ND_CE_arhtro.txt")
print(summary(lm.out))
print(summary(lm.out1))

#regression for critically endangered arthropoda using mitochondiral diversity 
lm.out=lm(range~Nucleotide_diversity, data=data)
summary(lm.out)
lm.out1=lm(latitude+longitude~Nucleotide_diversity, data=data)
summary(lm.out1)
pdf("MD_CE_arhtro.pdf", width=5, height=5)
plot(x=data$range, y=data$Nucleotide_diversity, xlab="range", ylab="Mitochondrial diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Nucleotide_diversity, xlab="latlong", ylab="Mitochondrial diveristy")
abline(lm.out1)
dev.off()
sink("MD_CE_arhtro.txt")
print(summary(lm.out))
print(summary(lm.out1))
sink()

#regression for endangered arthropoda using nuclear diveristy
pdf("ND_EN_arhtro.pdf", width=5, height=5)
data=read.table("arhtro_EN.csv", header=T, sep=",")
lm.out=lm(range~Observed_Heterozygosity, data=data)
summary(lm.out)
lm.out1=lm(latitude+longitude~Observed_Heterozygosity, data=data)
summary(lm.out1)
plot(x=data$range, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Observed_Heterozygosity, xlab="range", ylab="Nuclear diversity")
abline(lm.out1)
dev.off()
sink("ND_EN_arhtro.txt")
print(summary(lm.out))
print(summary(lm.out1))

#regression for endangered arthropoda using mitochondrail diveristy
lm.out=lm(range~Nucleotide_diversity, data=data)
summary(lm.out)
lm.out1=lm(latitude+longitude~Nucleotide_diversity, data=data)
summary(lm.out1)
pdf("MD_EN_arhtro.pdf", width=5, height=5)
plot(x=data$range, y=data$Nucleotide_diversity, xlab="range", ylab="Mitochondrial diversity")
abline(lm.out)
plot(x=data$latitude+data$longitude, y=data$Nucleotide_diversity, xlab="latlong", ylab="Mitochondrial diveristy")
abline(lm.out1)
dev.off()
sink("MD_EN_arhtro.txt")
print(summary(lm.out))
print(summary(lm.out1))
sink()